AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/initializers/*'
    - 'spec/features/screenshots.rb'
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Metrics/AbcSize:
  Max: 30
