AllCops:
  TargetRailsVersion: 4.2
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/initializers/*'
    - 'spec/features/screenshots.rb'
    - 'config/routes.rb'
Rails:
  Enabled: true

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/markdown_helper.rb'
    - 'app/mailers/seller_mailer.rb'

Style/FormatStringToken:
  Exclude:
    - 'app/models/item.rb'

# Time.zone is nil when executing rake tasks in production environment
Rails/TimeZone:
  Enabled: false
