inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-faker

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 4.2
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/initializers/*'
    - 'spec/features/screenshots.rb'
    - 'config/routes.rb'
Rails:
  Enabled: true

Metrics/ClassLength:
  Max: 170

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 38

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/markdown_helper.rb'
    - 'app/mailers/seller_mailer.rb'
    - 'app/mailers/notification_mailer.rb'

Style/FormatStringToken:
  Exclude:
    - 'app/models/item.rb'

# Time.zone is nil when executing rake tasks in production environment
Rails/TimeZone:
  Enabled: false

Rails/Date:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
  - 'spec/views/**/*'
  - 'spec/features/**/*'
  - 'spec/requests/**/*'

RSpec/ScatteredSetup:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

# we cannot specify dependent: :destroy as this would destroy relations also during soft deletes
Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/category.rb'
    - 'app/models/seller.rb'

Metrics/ParameterLists:
  CountKeywordArgs: false

Rails/RakeEnvironment:
  Exclude:
    - 'lib/capistrano/tasks/*.rake'
