# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
<% if ENV['DB'] == 'mysql' %>
default: &default
  adapter: mysql2
  encoding: utf8
  database: flohmarkthelfer
  username: flohmarkthelfer
  password: flohmarkthelfer
  host: 127.0.0.1
  port: 3306
  secure_auth: false
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
<% else %>
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
<% end %>
