brands:
  default:
    name: Flohmarkthelfer
    name_html: Flohmarkt<strong>helfer</strong>
    home:
    contact: hilfe@flohmarkthelfer.de
    imprint:
      address:
        - Fam. Lehmann
        - Am Schlossgarten 14
        - 75203 Königsbach
      contact: imprint@flohmarkthelfer.de
    terms: |
      Der Anbieter stellt eine Webseite zur Verfügung, über die sich Interessenten zum Verkauf von Ware auf
      Kommissionsflohmärkten anmelden können. Die Platform bietet die Möglichkeit
      der Warenverwaltung inklusive Etikettendruck mit Barcodes, sowie zur Benachrichtigung über stattfindende
      Flohmärkte und der Abwicklung.

      Es gibt des weiteren einen für Organisationsteams geschützten Bereich, mit dem diese Ihre Flohmärkte verwalten
      und für die Interessierte Verkäuferplätze reservieren können. Es obliegt den Organisationsteams:

      - separate Teilnahmebedingungen für die Flohmärkte zu definieren
      - individuelle Verkäufer zu priorisieren oder auszuschließen
      - Verkäufer über den Ablauf der Flohmärkte zu informieren
      - die Organisation des Flohmarkts inklusive Warenannahme, -rückgabe und Verkaufsabwicklung durchzuführen

      Die Platform stellt Dienstleistungen für

      - Flohmarktverwaltung
      - Artikelverwaltung
      - Kommunnikation
      - Kassensystem
      - Abrechnung

      zur Verfügung. Der Anbieter ist nicht verwantwortlich für die Durchführung der Flohmärkte selbst.
    mail:
      from: Flohmarkthelfer <info@flohmarkthelfer.de>
    price_precision: 0.1
    commission_rate: 0.2
    seller_fee: 2.0
