brands:
  default:
    name: Flohmarkthelfer
    name_html: Flohmarkt<strong>helfer</strong>
    home:
    contact: hilfe@flohmarkthelfer.de
    imprint:
      address:
        - Fam. Lehmann
        - Am Schlossgarten 14
        - 75203 Königsbach
      contact: imprint@flohmarkthelfer.de
    terms: |
      Der Anbieter stellt eine Webseite zur Verfügung, über die sich Interessenten zum Verkauf von Ware auf
      Kommissionsflohmärkten anmelden können. Die Platform bietet die Möglichkeit
      der Warenverwaltung inklusive Etikettendruck mit Barcodes, sowie zur Benachrichtigung über stattfindende
      Flohmärkte und der Abwicklung.

      Es gibt des weiteren einen für Organisationsteams geschützten Bereich, mit dem diese Ihre Flohmärkte verwalten
      und für die Interessierte Verkäuferplätze reservieren können. Es obliegt den Organisationsteams:

      - separate Teilnahmebedingungen für die Flohmärkte zu definieren
      - individuelle Verkäufer zu priorisieren oder auszuschließen
      - Verkäufer über den Ablauf der Flohmärkte zu informieren
      - die Organisation des Flohmarkts inklusive Warenannahme, -rückgabe und Verkaufsabwicklung durchzuführen

      Die Platform stellt Dienstleistungen für

      - Flohmarktverwaltung
      - Artikelverwaltung
      - Kommunnikation
      - Kassensystem
      - Abrechnung

      zur Verfügung. Der Anbieter ist nicht verwantwortlich für die Durchführung der Flohmärkte selbst.
    mail:
      from: Flohmarkthelfer <info@flohmarkthelfer.de>
  koenigsbach:
    name: Flohmarkt Königsbach
    name_html: Flohmarkt Königsbach
    home:
      logo:
        - koenigsbach/logo/kitaregenbogen.jpg
        - koenigsbach/logo/archenoahkita.jpg
      outro: |
        <small>Hier noch ein paar Impressionen unseres Flohmarkts in der Festhalle Königsbach</small>

        ![](koenigsbach/images/flohmarkt.jpg)
        ![](koenigsbach/images/flohmarkt2.jpg)
        ![](koenigsbach/images/kinderbetreuung.jpg)
    contact: hilfe@flohmarkt-koenigsbach.de
    imprint:
      address:
        - Fam. Lehmann
        - Am Schlossgarten 14
        - 75203 Königsbach
      contact: imprint@flohmarkt-koenigsbach.de
    terms: |
      **In Kommission genommen werden** gut erhaltene, gewaschene Baby- und Kinderbekleidung
      für die kommende Jahreszeit bis Größe 176, Umstandsmode, Schuhe, Kinderbetten, Kinderwägen, Buggys,
      Autositze, Rutschautos, Kettcars, Fahrräder, Spielsachen etc.

      ### WICHTIG!

      Die Ware muss ...

      1. zuvor in unserem Warensystem komplett eingetragen worden sein,
      2. einzeln mit dem entsprechenden Etikett ausgezeichnet sein.
         **Der Barcode und die Zahl darunter muss vollständig lesbar und sauber sein.**
         **Es werden nur Etiketten akzeptiert, die mit unserem System erzeugt wurden.**
      3. in einem **Karton/Wäschekorb** angeliefert werden, der mit der
         **Teilnehmernummer gut sichtbar** gekennzeichnet ist (mehrteilige Kleidungsstücke bitte zusammennähen),
      4. in einem **einwandfreien und zeitgemäßen Zustand** sein

      Falsch ausgezeichnete Ware oder solche mit abgefallenen Etiketten kann von uns leider nicht verkauft werden.
      Wir legen Wert auf einwandfreie, zeitgemäße Ware und behalten uns vor, Teile auszusortieren.

      Für die abgegebene Ware kann (bei Beschädigung und Diebstahl) **keine Haftung** übernommen werden.
      Für die Rückgabe von Kleiderbügeln kann keine Gewähr übernommen werden.

      Es entfällt pro Teilnehmer eine **Teilnahmegebühr** von **2,50 €**.

      **Wir runden alle Verkäuferauszahlungsbeträge ab** auf volle 10 Cent. D.h. aus 10,88 € wird 10,80 €.

      Nur ein Teilnehmer je Haushalt. Mehrere Anmeldungen des gleichen Haushaltes sind nicht gestattet.
      Wir behalten uns das Recht vor, Mehrfachreservierungen aus dem gleichen Haushalt wieder freizugeben.

      Es werden nur Preise akzeptiert, die auf 10 Cent gerundet sind.

      Die Teilnehmer müssen die nicht verkaufte Ware, sowie den Erlös der verkauften Teile **sofort kontrollieren**.
      Eine spätere Reklamation ist nicht zulässig.

      Sollte Ihre nicht verkaufte Ware bis zum Ende des für den Flohmarkt festgelegten Abholzeitraums
      **nicht abgeholt** sein, betrachten wir die Ware als **Spende**.

      ### Drucken der Etiketten

      Wir arbeiten beim Verkauf mit Scannern und akzeptieren daher nur Waren mit unseren Etiketten,
      welche Sie nach Artikeleingabe erzeugen und drucken.

      Sollten Sie keine Möglichkeit zum Drucken haben, befestigen Sie bitte Papierschilder mit der Größe von
      min. 7x5 cm an Ihren Artikeln und beschriften diese mit der Positionsnr. oder Artikelnummer.
      Sie bekommen bei der Annahme von uns Etikettenaufkleber um diese zu überkleben.
      Wir behalten uns vor, für diesen Service 2,00 € zu berechnen.

      Handschriftliche Änderungen auf den Etiketten werden nicht akzeptiert.
      Das System kennt nur die Werte, welche online eingegeben wurden.

      Bitte verwenden Sie für den Druck **kein rotes oder sehr dunkles Papier**.

      Die Etiketten dürfen laminiert oder geklebt werden, sofern dies nicht die Ware beschädigt.

      ### Verkaufserlös

      Als Unkostenbeitrag behalten wir **20%** des Erlöses ein, der nach Abzug der Kosten den
      Kindergärten Regenbogen und Arche Noah zu gleichen Teilen gespendet wird.
    mail:
      from: Flohmarkt Königsbach <info@flohmarkt-koenigsbach.de>
  ersingen:
    name: Flohmarkt Ersingen
    name_html: Flohmarkt Ersingen
    home:
      logo:
        - ersingen/logo/kita-ersingen.png
      outro: |
        ![](ersingen/images/flohmarkt-ersingen.jpg)

        Mit freundlicher Empfehlung

        ![](ersingen/images/raibaersingen.jpg)
    contact: hilfe@flohmarkt-ersingen.de
    imprint:
      address:
        - Jana Vielsack
        - Pforzheimer Str. 14
        - 75236 Kämpfelbach
      contact: imprint@flohmarkt-ersingen.de
    terms: |
      **In Kommission genommen werden** gut erhaltene, gewaschene Baby- und Kinderbekleidung
      für die kommende Jahreszeit bis Größe 176, Umstandsmode, Schuhe, Kinderbetten, Kinderwägen, Buggys,
      Autositze, Rutschautos, Kettcars, Fahrräder, Spielsachen etc.

      ### WICHTIG!

      Die Ware muss ...

      1. zuvor in unserem Warensystem komplett eingetragen worden sein,
      2. einzeln mit dem entsprechenden Etikett ausgezeichnet sein.
         **Der Barcode und die Zahl darunter muss vollständig lesbar und sauber sein.**
         **Es werden nur Etiketten akzeptiert, die mit unserem System erzeugt wurden.**
      3. in einem **Karton/Wäschekorb** angeliefert werden, der mit der
         **Teilnehmernummer gut sichtbar an einer der Stirnseiten** gekennzeichnet ist
         (mehrteilige Kleidungsstücke bitte zusammennähen),
      4. in einem **einwandfreien und zeitgemäßen Zustand** sein

      Falsch ausgezeichnete Ware oder solche mit abgefallenen Etiketten kann von uns leider nicht verkauft werden.
      Wir legen Wert auf einwandfreie, zeitgemäße Ware und behalten uns vor, Teile auszusortieren.

      Für die abgegebene Ware kann (bei Beschädigung und Diebstahl) **keine Haftung** übernommen werden.
      Für die Rückgabe von Kleiderbügeln kann keine Gewähr übernommen werden.

      Es entfällt pro Teilnehmer eine **Teilnahmegebühr** von **2,50 €**.

      **Wir runden alle Verkäuferauszahlungsbeträge ab** auf volle 10 Cent. D.h. aus 10,88 € wird 10,80 €.

      Nur ein Teilnehmer je Haushalt. Mehrere Anmeldungen des gleichen Haushaltes sind nicht gestattet.
      Wir behalten uns das Recht vor, Mehrfachreservierungen aus dem gleichen Haushalt wieder freizugeben.

      Es werden nur Preise akzeptiert, die auf 10 Cent gerundet sind.

      Die Teilnehmer müssen die nicht verkaufte Ware, sowie den Erlös der verkauften Teile **sofort kontrollieren**.
      Eine spätere Reklamation ist nicht zulässig.

      Sollte Ihre nicht verkaufte Ware bis zum Ende des für den Flohmarkt festgelegten Abholzeitraums
      **nicht abgeholt** sein, betrachten wir die Ware als **Spende**.

      ### Drucken der Etiketten

      Wir arbeiten beim Verkauf mit Scannern und akzeptieren daher nur Waren mit unseren Etiketten,
      welche Sie nach Artikeleingabe erzeugen und drucken.

      Sollten Sie keine Möglichkeit zum Drucken haben, befestigen Sie bitte Papierschilder mit der Größe von
      min. 7x5 cm an Ihren Artikeln und beschriften diese mit der Positionsnr. oder Artikelnummer.
      Sie bekommen bei der Annahme von uns Etikettenaufkleber um diese zu überkleben.
      Wir behalten uns vor, für diesen Service 2,00 € zu berechnen.

      Handschriftliche Änderungen auf den Etiketten werden nicht akzeptiert.
      Das System kennt nur die Werte, welche online eingegeben wurden.

      Bitte verwenden Sie für den Druck kein rotes oder sehr dunkles Papier

      Die Etiketten dürfen laminiert oder geklebt werden, sofern dies nicht die Ware beschädigt.

      ### Verkaufserlös

      Als Unkostenbeitrag behalten wir **20%** des Erlöses ein, der nach Abzug der Kosten
      dem Kindergarten gespendet wird.
    mail:
      from: Flohmarkt Ersingen <info@flohmarkt-ersingen.de>
  dammerstock:
    name: Flohmarkt Friedensgemeinde
    name_html: Flohmarkt Friedensgemeinde
    home:
      logo:
      outro: |
        <small>Hier noch ein paar Impressionen unseres Flohmarkts</small>

        ![](dammerstock/images/image1.jpg)
        ![](dammerstock/images/image2.jpg)
        ![](dammerstock/images/image3.jpg)
        ![](dammerstock/images/image4.jpg)
    contact: friedensgemeinde@flohmarkthelfer.de
    imprint:
      address:
        - Evangelische Friedensgemeinde Weiherfeld-Dammerstock
        - Tauberstraße 8
        - 76199 Karlsruhe
      contact: friedensgemeinde@flohmarkthelfer.de
    terms: |
      **In Kommission genommen werden** gut erhaltene, gewaschene Baby- und Kinderbekleidung für die kommende
      Jahreszeit bis Größe 176, Umstandsmode, Schuhe, Kinderwägen, Buggys, Autositze, Rutschautos, Kettcars,
      Fahrräder, Spielsachen etc.

      ### WICHTIG!

      Die Ware muss...

      1. zuvor in unserem Warensystem komplett eingetragen worden sein,
      2. einzeln mit dem entsprechenden Etikett ausgezeichnet sein.
         **Der Barcode und die Zahl darunter müssen vollständig lesbar und sauber sein.**
         **Es werden nur Etiketten akzeptiert, die mit unserem System erzeugt wurden.**
      3. in einem **Karton/Wäschekorb** angeliefert werden, der mit der **Teilnehmernummer gut sichtbar**
         gekennzeichnet ist.
      4. in einem **einwandfreien Zustand** sein

      Es dürfen pro Anbieter eine begrenzte Anzahl von Artikeln in Kommission gegeben werden.

      Bitte sorgen Sie dafür, dass Ihre Etiketten gut befestigt sind, da wir für Verlust oder Vertauschen
      derselben nicht haften können.

      Falsch ausgezeichnete Ware oder solche mit abgefallenen Etiketten kann von uns leider nicht verkauft werden.
      Wir legen Wert auf einwandfreie (nicht verschmutzte) Ware und behalten uns vor, Teile auszusortieren.

      Für die abgegebene Ware kann (bei Beschädigung und Diebstahl) **keine Haftung** übernommen werden.
      Kleiderbügel werden nicht zurück gegeben.

      **Wir runden alle Verkäuferauszahlungsbeträge ab** auf volle 50 Cent. D.h. aus 10,88 € werden 10,50 €.

      Es werden nur Preise akzeptiert, die auf 50 Cent gerundet sind.

      Die Teilnehmer müssen die nicht verkaufte Ware, sowie den Erlös der verkauften Teile **sofort kontrollieren**.

      **Nicht zurücksortiert** und damit als **Spende** betrachtet werden: Schuhe und Accessoires, wie z.B.
      Gürtel, Unterwäsche, Bodies, Strumpfhosen, Socken, Mützen, Schals, Handschuhe, Badekleidung.

      Sollte Ihre nicht verkaufte Ware und der Erlös bis zum Ende des für den Flohmarkt festgelegten Abholzeitraums
      **nicht abgeholt** sein, betrachten beides als **Spende**.
      Gerne können Sie uns dies auch vorab per E-Mail mitteilen.

      ### Drucken der Etiketten

      Wir arbeiten beim Verkauf mit Scannern und akzeptieren daher nur Waren mit unseren Etiketten,
      welche Sie nach Artikeleingabe erzeugen und ausdrucken können.

      Handschriftliche Änderungen auf den Etiketten werden nicht akzeptiert.
      Das System kennt nur die Werte, welche online eingegeben wurden.

      Bitte verwenden Sie für den Druck **kein rotes oder sehr dunkles Papier**.

      Die Etiketten dürfen laminiert oder auf festeren Karton geklebt werden.

      Sollten Sie keine Möglichkeit haben, die Etiketten selbst zu drucken, kontaktieren Sie uns bitte.

      ### Verkaufserlös

      Als Unkostenbeitrag behalten wir 25% des Erlöses ein, der nach Abzug der Kosten für gemeinnützige bzw.
      soziale Zwecke gespendet wird (siehe Aushang).
    mail:
      from: Flohmarkt Friedensgemeinde Weiherfeld-Dammerstock <friedensgemeinde@flohmarkthelfer.de>
hosts:
  koenigsbach.localhost: koenigsbach
  ersingen.localhost: ersingen
  dammerstock.localhost: dammerstock
