downloads:
  client: https://flohmarkthelfer.de/download/flohmarkthelfer-setup.exe
  mobile: https://flohmarkthelfer.de/download/flohmarkthelfer.apk
domain: flohmarkthelfer.de
imprint:
  address:
    - Lehmann Softwarelösungen
    - Essenweinstraße 19
    - 76131 Karlsruhe
  contact: imprint@flohmarkthelfer.de
bill:
  title: FLOHMARKTHELFER
  issuer:
    phone: '+49 1523 378 9600'
    email: rechnung@flohmarkthelfer.de
    web: 'https://flohmarkthelfer.de'
    bank: 'IBAN: DE42 1234 5678 1234 5678 42 / BIC: HELADEF1234'
    name: Kai Lehmann
    company: Lehmann Softwarelösungen
    address:
      - Lehmann Softwarelösungen
      - Essenweinstraße 19
      - 76131 Karlsruhe
default_client:
  name: Flohmarkthelfer
  short_name: Flohmarkt<strong>helfer</strong>
  contact: hilfe@flohmarkthelfer.de
  mail_address: hilfe@flohmarkthelfer.de
  terms: |
    ### Dienstleistung

    Der Anbieter stellt eine Webseite zur Verfügung, über die sich Interessenten zum Verkauf von Ware auf
    Kommissionsflohmärkten anmelden können. Die Platform bietet die Möglichkeit
    der Warenverwaltung inklusive Etikettendruck mit Barcodes, sowie zur Benachrichtigung über stattfindende
    Flohmärkte und der Abwicklung.

    Es gibt des weiteren einen für Organisationsteams geschützten Bereich, mit dem diese Ihre Flohmärkte verwalten
    und für die Interessierte Verkäuferplätze reservieren können. Es obliegt den Organisationsteams:

    - separate Teilnahmebedingungen für die Flohmärkte zu definieren
    - individuelle Verkäufer zu priorisieren oder auszuschließen
    - Verkäufer über den Ablauf der Flohmärkte zu informieren
    - die Organisation des Flohmarkts inklusive Warenannahme, -rückgabe und Verkaufsabwicklung durchzuführen

    Die Platform stellt Dienstleistungen für

    - Flohmarktverwaltung
    - Artikelverwaltung
    - Kommunnikation
    - Kassensystem
    - Abrechnung

    zur Verfügung. Der Anbieter ist nicht verwantwortlich für die Durchführung der Flohmärkte selbst.

    ### Verfügbarkeit

    Das System steht in der Regel mit Ausnahme von geplanten Wartungsarbeiten jederzeit Verfügung. Es wird versucht,
    eine Verfügbarkeit von 99,7% zu erreichen. Da der Anbieter von Dritten hinsichtlich der verwendeten
    Platform und Hardware abhängig ist, kann diese Verfügbarkeit nicht garantiert werden.

    Der Anbieter ist für die Bereitstellung des Systems auf Dritte (Internetprovider, Hostingprovider, Mailprovider)
    angewiesen. Der Anbieter haftet nicht für Ausfälle oder Datenverlust, der durch Dritte entstanden ist.
    Es werden in regelmäßigen Abständen Sicherheistkopien der Daten erstellt, welche bei einem Totalsystemausfall
    auf einem Ersatzsystem zur Verfügung gestellt werden können.

    ### Haftung

    Der Anbieter haftet nicht für Inhalte, die durch Nutzer (Verkäufer, Verwalter) entstehen. Die Nutzer haften selbst
    für ihre Inhalte.

    ### Ende der Dienstleistung

    Der Anbieter behält sich vor, die Dienstleistung jederzeit zu beenden. Dies wird jedoch mindestens 4 Wochen vor
    Beendigung der Dienstleistung vom Anbieter an alle dem Anbieter bekannten Verwalter per Mail mitgeteilt.
    Im Falle der Beendigung der Dienstleistung haben die Verwalter das Recht, vom Anbieter eine Sicherheitskopie der
    Datenbank für ihren Flohmarkt zu verlangen.
mail:
  from: Flohmarkthelfer <info@flohmarkthelfer.de>
