brands:
  bobingen:
    name: Kindergarten "Zur Heiligen Familie"
    name_html: KiTa "Zur Heiligen Familie"
    home:
      logo:
      intro: |
        Sommerstraße 12<br/>
        Bobingen OT Siedlung

        **!Neu! Als Unkostenbeitrag behalten wir 10% des Umsatzes ein, der nach Abzug der Kosten den Kindergarten
        "Zur Heiligen Familie" gespendet wird.
        Bitte beachten Sie, dass diese 10% von Ihrem ausgewiesenen Verkaufspreis abgezogen werden.**
      outro: |
        ![](bobingen/images/flyer201603.png)

        So finden Sie uns:

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2655.497524536614!2d10.795871315801636!3d48.274043549625006!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479ea16c61f9ad1d%3A0x5dac81587b3c9e21!2sKath.+Heilige+Familie+Kindergarten!5e0!3m2!1sen!2sde!4v1455913637961" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    contact: kita-zhf@flohmarkthelfer.de
    imprint:
      address:
        - Lehmann Software Lösungen GbR
        - Am Schlossgarten 14
        - 75203 Königsbach
      contact: imprint@flohmarkthelfer.de
    terms: |
      Sie registrieren sich auf unserer Website als potenzieller Verkäufer.
      Erst mit der Reservierung (Infos erhalten Sie nach der Anmeldung)
      bestellen Sie eine oder mehrere Listen.

      <u>Kosten für eine Liste mit 40 Artikeln: **5,- €.**</u><br/>
      Jeder Verkäufer kann maximal 4 Listen
      reservieren. Es wird eine limitierte Anzahl von Listen vergeben. Die Gebühren werden von den
      Einnahmen abgezogen und direkt einbehalten.

      Um Ihnen Ihre Verkäufernummer zukommen zu lassen und Sie bei spontanen
      Änderungen schnell informieren zu können, benötigen wir Ihre Kontaktangaben. Bitte
      achten Sie vor dem Absenden auf eine korrekte Schreibweise aller Eingaben.

      **Verkauft werden können gut erhaltene, modische Artikel,
      der Jahreszeit entsprechend, ohne Flecken oder Beschädigungen,
      und die keine Mängel haben!**

      - Autositze (ECE R44/03 und ECE R44/04), Türschutzgitter
      - Fahrräder: (Verkehrs- und funktionstüchtig – bringen Sie bitte einen Zettel mit Ihrer Adresse und
        Telefonnummer an, damit der Käufer den rechtmäßigen Besitz nachweisen kann.)
      - gebrauchte Kinderfahrzeuge, Puppenwagen und Kinderwägen
      - Spielsachen, Freizeitartikel
      - Spiele, Brettspiele, Kinderbücher, Puzzle, Cd´s, DVD`s
      - Kaufladen, Kinderküche, Puppen, Autos, Werkbank
      - Kindermöbel und Zubehör (z.B. Hochstuhl, Babywippe, Reisebett, ...)
      - Kinderkleidung (nur Saisonart) von Größe 50 – 164
      - Schuhe, geputzt (nur Saisonart)
      - Umstandsmoden

      Die Ware soll sauber sein, gebügelt, frei von Tierhaaren, Reißverschlüsse müssen
      funktionieren und alle Knöpfe müssen fest sitzen.

      <u>Nicht angenommen werden:</u>

      - Unterhosen, Windeln, gebrauchte WC Aufsätze und Töpfchen,
      - Trinkbecher, Flaschen und Nahrungsmittel etc.
      - Still- Büstenhalter und Milchpumpen
      - Kleidung mit herausgeschnittenen Etiketten, deren Größe augenscheinlich 164 übersteigt

      **WIR BEHALTEN UNS VOR, STICHPROBEN ZU MACHEN!**

      **Es wird nur vollständiges Spielzeug zum Verkauf angeboten.**

      ### Drucken der Etiketten

      Wir arbeiten beim Verkauf mit Scannern und akzeptieren daher nur Waren mit
      unseren Etiketten, welche Sie nach Artikeleingabe erzeugen und drucken.

      Handschriftliche Änderungen auf den Etiketten werden nicht akzeptiert. Das System
      kennt nur die Werte, welche Online eingegeben wurden.

      Bitte verwenden Sie für den Druck möglichst helles Papier.
      Die Etiketten dürfen laminiert werden.

      ### Bitte beachten Sie

      <u>Auf jedem Etikett</u> muss der von Ihnen verlangte <u>Preis
      **(_inklusive_ 10%, die als Erlös an den Kindergarten gehen und Ihrer Rechnung am Schluss
      abgezogen werden)**</u>, sowie die <u>Bezeichnung</u> stehen.
      Bei Kleidung und Schuhen geben Sie bitte auch eine <u>Größe</u> an.

      Es werden nur Preise akzeptiert, die auf 10 Cent gerundet sind.

      Befestigen Sie an jedem Artikel das zugehörige Etikett mit einer Paketschnur,
      reißfestem Faden, Geschenkband oder fester Wolle, nach Möglichkeit entweder am
      Knopfloch, Größenetikett, Label oder an der Gürtelschlaufe.<br/>
      <u>Bitte nicht tackern – keine Stecknadeln – keine Sicherheitsnadeln – keine Heftklammern!</u><br/>
      (Es empfiehlt sich das Etikett z.B. mit Klebeband an der Befestigungsstelle zu verstärken,
      um das einreißen des Etikettes zu vermeiden.)

      <u>Befestigung</u> an Büchern, CD`s, Spielen / Puzzles usw: Wie ein Paket mit Faden
      verschnüren und daran das Etikett festbinden. Vorteil: durch das Verschnüren kann
      niemand die Schachtel öffnen und Teile können nicht verloren gehen.<br/>
      <u>**Das Etikett bitte nicht festkleben**</u>, da der Artikel dadurch beschädigt
      werden könnte und der Käufer diesen evtl. nicht mehr erwerben will.

      Bitte bieten Sie elektronisches Spielzeug in geeigneten Verpackungen an. Diese
      müssen mit <u>"funktioniert" oder "vollständig"</u> gekennzeichnet sein und auch diese
      Eigenschaften aufweisen.
      Bitte bieten Sie der Fairness halber keine defekten elektronischen Spielsachen an.
      Darüber hinaus kann der Verkäufer über die Artikellisten jederzeit ermittelt werden.

      **Mehrteilige Artikel** bitte nur mit **einem Etikett** versehen und die **Anzahl der Teile
      in der Artikelbeschreibung vermerken**. Anschließend die Teile fest miteinander verbinden
      (nicht mit Nadeln!).

      _Sie versehen Ihre Artikel mit den entsprechenden Preisschildern und verpacken alles
      in einem mit Ihrer Verkäufernummer (Reservierungsnummer) versehenen Kiste._

      **Bitte Ware nur in <u>Kunststoffbox, Wäschekorb</u> oder am besten in <u>Klappkiste(n)</u>**
      anliefern.<br/>
      Die Box muss <u>vorn</u> und <u>hinten</u> gut leserlich mit der Verkäufernummer (Reservierungsnummer),
      am Besten auf einem an der Box festgebundenen Karton versehen werden. Die Kiste wird für die
      Rückgabe einbehalten.<br/>
      <u>Windelkartons oder Plastiktüten sind nicht gestattet.</u>

      <font color=#cc0099>**Wir nehmen Ihre Kiste und größeren Einzelartikel
      in der Regel am Tag vor dem Verkaufstag entgegen.**

      Die Abholung der nicht verkauften Ware und des Erlöses erfolgt in der Regel
      wenige Stunden nach Verkaufsschluss.

      **Termine zu jedem Flohmarkt finden Sie auf der Startseite in den Termindetails.**</font>

      ### Einverständniserklärung
      Indem Sie Kleider oder Gegenstände zum Verkauf anbieten, erklären Sie sich mit
      den folgenden Bedingungen einverstanden:

      - Kleidung und Gegenstände, die nicht während der angegebenen Abholzeiten geholt
        werden, führen wir einem wohltätigen Zweck zu.
      - Bei Abholung bitte selbstständig <u>nummerlose Gegenstände</u> durchschauen, nur
        Eigentum mitnehmen!
      - Wir übernehmen **KEINE GARANTIE** für den Verkauf.
      - <u>**KEINERLEI Haftung**</u> für Ware, die verloren gegangen ist, beschädigt, gestohlen
      wurde oder Artikel bei denen sich die Preisschilder lösten. Die Abgabe der Ware
      erfolgt auf eigene Gefahr.
      - <u>**REKLAMATIONEN**</u> ( bezüglich der Abrechnung) nehmen wir nur direkt bei
        Abholung entgegen.<br/>
        <u>_Spätere Reklamationen können wir leider nicht berücksichtigen!_</u>

      <u>_Als Unkostenbeitrag behalten wir 10% des Umsatzes ein, der nach Abzug der
      Kosten den Kindergarten „Zur Heiligen Familie“ gespendet wird. Bitte beachten Sie,
      dass diese 10% von Ihrem ausgewiesenen Verkaufspreis abgezogen werden._</u>

      **Sollten Sie doch nicht teilnehmen können, so geben Sie bitte Ihren Verkäuferplatz (unter
      Ihrem persönlichen Bereich) so schnell wie möglich wieder frei, damit wird Ihr Platz neu vergeben.**

      Bei Abholung bitte den Abholschein vorlegen.

      <u>_Mit Ihrer Unterschrift bei der Abgabe der Ware akzeptieren Sie die obigen
      Bedingungen!_</u>

      _Sollten diese Punkte nicht eingehalten werden, wird die Ware nicht angenommen!_
    mail:
      from: Flohmarkt KiTa Zur Heiligen Familie <kita-zhf@flohmarkthelfer.de>
    price_precision: 0.1
    commission_rate: 0.1
    seller_fee: 5.0
    donation_of_unsold_items_enabled: false
    prefix: 4
hosts:
  bobingen.localhost: bobingen
  bobingen.flohmarkthelfer.de: bobingen
  kita-zhf.flohmarkthelfer.de: bobingen
  www.kita-zhf.flohmarkthelfer.de: bobingen
