brands:
  dammerstock:
    name: Flohmarkt Friedensgemeinde
    name_html: Flohmarkt Friedensgemeinde
    home:
      logo: dammerstock/logo/friedenskirche.png
      outro: |
        <small>Hier noch ein paar Impressionen unseres Flohmarkts</small>

        ![](dammerstock/images/image1.jpg)
        ![](dammerstock/images/image2.jpg)
        ![](dammerstock/images/image3.jpg)
        ![](dammerstock/images/image4.jpg)
    contact: friedensgemeinde@flohmarkthelfer.de
    imprint:
      address:
        - Evangelische Friedensgemeinde Weiherfeld-Dammerstock
        - Tauberstraße 8
        - 76199 Karlsruhe
      contact: friedensgemeinde@flohmarkthelfer.de
    terms: |
      **In Kommission genommen werden** gut erhaltene, gewaschene Baby- und Kinderbekleidung für die kommende
      Jahreszeit bis Größe 176, Umstandsmode, Schuhe, Kinderwägen, Buggys, Autositze, Rutschautos, Kettcars,
      Fahrräder, Spielsachen etc.

      ### WICHTIG!

      Die Ware muss...

      1. zuvor in unserem Warensystem komplett eingetragen worden sein,
      2. einzeln mit dem entsprechenden Etikett ausgezeichnet sein.
         **Der Barcode und die Zahl darunter müssen vollständig lesbar und sauber sein.**
         **Es werden nur Etiketten akzeptiert, die mit unserem System erzeugt wurden.**
      3. in einem **Karton/Wäschekorb** angeliefert werden, der mit der **Teilnehmernummer gut sichtbar**
         gekennzeichnet ist.
      4. in einem **einwandfreien Zustand** sein

      Es dürfen pro Anbieter eine begrenzte Anzahl von Artikeln in Kommission gegeben werden.

      Bitte sorgen Sie dafür, dass Ihre Etiketten gut befestigt sind, da wir für Verlust oder Vertauschen
      derselben nicht haften können.

      Falsch ausgezeichnete Ware oder solche mit abgefallenen Etiketten kann von uns leider nicht verkauft werden.
      Wir legen Wert auf einwandfreie (nicht verschmutzte) Ware und behalten uns vor, Teile auszusortieren.

      Für die abgegebene Ware kann (bei Beschädigung und Diebstahl) **keine Haftung** übernommen werden.
      Kleiderbügel werden nicht zurück gegeben.

      **Wir runden alle Verkäuferauszahlungsbeträge ab** auf volle 50 Cent. D.h. aus 10,88 € werden 10,50 €.

      Es werden nur Preise akzeptiert, die auf 50 Cent gerundet sind.

      Die Teilnehmer müssen die nicht verkaufte Ware, sowie den Erlös der verkauften Teile **sofort kontrollieren**.

      **Nicht zurücksortiert** und damit als **Spende** betrachtet werden: Schuhe und Accessoires, wie z.B.
      Gürtel, Unterwäsche, Bodies, Strumpfhosen, Socken, Mützen, Schals, Handschuhe, Badekleidung.

      Sollte Ihre nicht verkaufte Ware und der Erlös bis zum Ende des für den Flohmarkt festgelegten Abholzeitraums
      **nicht abgeholt** sein, betrachten beides als **Spende**.
      Gerne können Sie uns dies auch vorab per E-Mail mitteilen.

      ### Drucken der Etiketten

      Wir arbeiten beim Verkauf mit Scannern und akzeptieren daher nur Waren mit unseren Etiketten,
      welche Sie nach Artikeleingabe erzeugen und ausdrucken können.

      Handschriftliche Änderungen auf den Etiketten werden nicht akzeptiert.
      Das System kennt nur die Werte, welche online eingegeben wurden.

      Bitte verwenden Sie für den Druck **kein rotes oder sehr dunkles Papier**.

      Die Etiketten dürfen laminiert oder auf festeren Karton geklebt werden.

      Sollten Sie keine Möglichkeit haben, die Etiketten selbst zu drucken, kontaktieren Sie uns bitte.

      ### Verkaufserlös

      Als Unkostenbeitrag behalten wir 25% des Erlöses ein, der nach Abzug der Kosten für gemeinnützige bzw.
      soziale Zwecke gespendet wird (siehe Aushang).
    mail:
      from: Flohmarkt Friedensgemeinde Weiherfeld-Dammerstock <friedensgemeinde@flohmarkthelfer.de>
    price_precision: 0.5
    commission_rate: 0.25
    seller_fee: 2.0
    donation_of_unsold_items_enabled: true
    prefix: 1
hosts:
  dammerstock.localhost: dammerstock
  dammerstock.flohmarkthelfer.de: dammerstock
  www.dammerstock.flohmarkthelfer.de: dammerstock
  friedensgemeinde.flohmarkthelfer.de: dammerstock
  www.friedensgemeinde.flohmarkthelfer.de: dammerstock
