brands:
  demo:
    name: Flohmarkthelfer Demo
    name_html: Flohmarkthelfer Demo
    home:
      logo:
      intro:
      outro: |
        **Festhalle Ankerstraße 11, 75203 Königsbach**

        Hier finden Sie uns:

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2619.402607693358!2d8.61125!3d48.964859999999994!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47970b5856c746a5%3A0xdadf1bab85854356!2sFesthalle!5e0!3m2!1sen!2sde!4v1438025681080" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

        <small>Hier noch ein paar Impressionen unseres Flohmarkts in der Festhalle Königsbach</small>

        ![](koenigsbach/images/flohmarkt.jpg)
        ![](koenigsbach/images/flohmarkt2.jpg)
        ![](koenigsbach/images/kinderbetreuung.jpg)
    contact: hilfe@flohmarkthelfer.de
    imprint:
      address:
        - Lehmann Software Lösungen
        - Essenweinstraße 19
        - 76131 Karlsruhe
      contact: imprint@flohmarkthelfer.de
    terms: |
      **In Kommission genommen werden** gut erhaltene, gewaschene Baby- und Kinderbekleidung
      für die kommende Jahreszeit bis Größe 176, Umstandsmode, Schuhe, Kinderbetten, Kinderwägen, Buggys,
      Autositze, Rutschautos, Kettcars, Fahrräder, Spielsachen etc.

      ### WICHTIG!

      Die Ware muss ...

      1. zuvor in unserem Warensystem komplett eingetragen worden sein,
      2. einzeln mit dem entsprechenden Etikett ausgezeichnet sein.
         **Der Barcode und die Zahl darunter muss vollständig lesbar und sauber sein.**
         **Es werden nur Etiketten akzeptiert, die mit unserem System erzeugt wurden.**
      3. in einem **Karton/Wäschekorb** angeliefert werden, der mit der
         **Teilnehmernummer gut sichtbar** gekennzeichnet ist (mehrteilige Kleidungsstücke bitte zusammennähen),
      4. in einem **einwandfreien und zeitgemäßen Zustand** sein

      Falsch ausgezeichnete Ware oder solche mit abgefallenen Etiketten kann von uns leider nicht verkauft werden.
      Wir legen Wert auf einwandfreie, zeitgemäße Ware und behalten uns vor, Teile auszusortieren.

      Für die abgegebene Ware kann (bei Beschädigung und Diebstahl) **keine Haftung** übernommen werden.
      Für die Rückgabe von Kleiderbügeln kann keine Gewähr übernommen werden.

      Es entfällt pro Reservierung eine **Reservierungsgebühr**.

      **Wir runden alle Verkäuferauszahlungsbeträge ab** auf volle 10 Cent. D.h. aus 10,88 € wird 10,80 €.

      Nur ein Teilnehmer je Haushalt. Mehrere Anmeldungen des gleichen Haushaltes sind nicht gestattet.
      Wir behalten uns das Recht vor, Mehrfachreservierungen aus dem gleichen Haushalt wieder freizugeben.

      Es werden nur Preise akzeptiert, die auf 10 Cent gerundet sind.

      Die Teilnehmer müssen die nicht verkaufte Ware, sowie den Erlös der verkauften Teile **sofort kontrollieren**.
      Eine spätere Reklamation ist nicht zulässig.

      Sollte Ihre nicht verkaufte Ware bis zum Ende des für den Flohmarkt festgelegten Abholzeitraums
      **nicht abgeholt** sein, betrachten wir die Ware als **Spende**.

      ### Drucken der Etiketten

      Wir arbeiten beim Verkauf mit Scannern und akzeptieren daher nur Waren mit unseren Etiketten,
      welche Sie nach Artikeleingabe erzeugen und drucken.

      Sollten Sie keine Möglichkeit zum Drucken haben, befestigen Sie bitte Papierschilder mit der Größe von
      min. 7x5 cm an Ihren Artikeln und beschriften diese mit der Positionsnr. oder Artikelnummer.
      Sie bekommen bei der Annahme von uns Etikettenaufkleber um diese zu überkleben.
      Wir behalten uns vor, für diesen Service 2,00 € zu berechnen.

      Handschriftliche Änderungen auf den Etiketten werden nicht akzeptiert.
      Das System kennt nur die Werte, welche online eingegeben wurden.

      Bitte verwenden Sie für den Druck **kein rotes oder sehr dunkles Papier**.

      Die Etiketten dürfen laminiert oder geklebt werden, sofern dies nicht die Ware beschädigt.

      ### Verkaufserlös

      Als Unkostenbeitrag behalten wir 20% des Umsatzes ein, der nach Abzug der Kosten den
      Kindergärten Regenbogen und Arche Noah zu gleichen Teilen gespendet wird.
    mail:
      from: Flohmarkthelfer Demo <demo@flohmarkthelfer.de>
    price_precision: 0.1
    commission_rate: 0.2
    seller_fee: 2.0
    donation_of_unsold_items_enabled: true
    prefix:
hosts:
  demo.localhost: demo
  demo.flohmarkthelfer.de: demo
  test.flohmarkthelfer.de: demo
  test.host: demo
  example.com: demo
