brands:
  durlach:
    name: Kommi-Flohmarkt Durlach
    name_html: Kommi-Flohmarkt Durlach
    home:
      logo:
        - durlach/images/logo_kommiflohmarkt_4c.jpg
      intro: |
        **Christ-König-Haus - Kanzlerstr. 5, 76227 Karlsruhe**

        Sie finden uns auch auf [Facebook](https://www.facebook.com/kommidurlach/).
      outro: |
        [Hier unser Plakat für den kommenden Flohmarkt](durlach/plakat.pdf)

        [Hier sind unsere Regelungen zum Aussetzen](durlach/regeln.pdf)

        Laden Sie sich die [Etikett-Vorlage für Ihren Karton](durlach/karton_etikett.pdf) herunter.

        Hier finden Sie uns:

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2617.670190723101!2d8.465691315860358!3d48.99783349883192!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479708e8d8d56691%3A0x8391688d96cd4fdc!2sKanzlerstra%C3%9Fe+5%2C+76227+Karlsruhe!5e0!3m2!1sen!2sde!4v1465115323668" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    contact: kommi-flohmarkt-durlach@flohmarkthelfer.de
    imprint:
      address:
        - Lehmann Software Lösungen GbR
        - Am Schlossgarten 14
        - 75203 Königsbach
      contact: imprint@flohmarkthelfer.de
    terms: |
      ### Allgemeines

      In Kommission genommen werden gut erhaltene, gewaschene Baby- und Kinderbekleidung
      für die *kommende Jahreszeit*, Umstandsmode, Schuhe, Kinderbetten, Kinderwägen, Buggys,
      Autositze, Rutschautos, Kettcars, Fahrräder, Bücher, CD’s, Spielsachen etc.

      ### Warensystem

      Die Ware muss in unserem Warensystem komplett
      eingetragen und mit dem entsprechenden Etiketten ausgezeichnet werden. Hierbei ist darauf
      zu achten, dass der Barcode und die Zahl auf dem Etikett vollständig und gut lesbar sind. Es
      werden nur Etiketten akzeptiert, die mit unserem System erzeugt wurden.

      ### Waren

      Falsch ausgezeichnete Ware oder solche mit abgefallenen Etiketten können von uns leider
      nicht verkauft werden. Artikel, die kein Preisschild haben, werden nicht verkauft.
      Um uns die Abrechnung zu vereinfachen, werden nur Preise akzeptiert, die auf 50 Cent
      gerundet sind. **(z.B. 1,00 €, 1,50 €, 2,00 €, ...)**.

      ### Verkaufserlös

      Die Teilnahme ist kostenlos. Vom Verkaufserlös erhalten Sie **70%**; **30% gehen an den
      Kommissionsflohmarkt Durlach, der den Erlös an eine gemeinnützige Einrichtung für
      Kinder spendet**.

      Sofern Sie uns mit Ihrem Arbeitseinsatz unterstützen, können Sie ihren Verkaufserlös steigern.
      Wer uns in einer Schicht (3 Stunden) unterstützt, der bekommt von seinem Verkaufserlös
      zusätzlich 5%. Wer bei zwei Schichten (6 Stunden) unterstützt, also freitags und samstags, der
      erhält 10% zusätzlich von seinem Verkaufserlös. Wer noch eine weitere Person zum Helfen
      mitbringt, z.B. die Tochter, Ehemann, Schwiegersohn usw. erhält auch für diesen Helfer nochmals
      die Prozente.

      Zusätzlich dürfen Helfer am Samstag bereits um 8:30 Uhr noch vor den Schwangeren (9:00 Uhr)
      auf den Flohmarkt.

      Wir werden die Anbieter im Vorfeld des Flohmarktes separat kontaktieren, ob Interesse
      besteht, uns zu unterstützen.

      Wir runden alle Verkäuferauszahlungsbeträge auf volle 50 Cent ab. D.h. aus 10,88 € wird 10,50 €.

      ### Preisschilder

      Wir arbeiten beim Verkauf mit Scannern und akzeptieren daher nur Waren, die mit unseren
      Barcode-Etiketten ausgezeichnet sind. Handschriftliche Änderungen auf den Etiketten
      werden nicht akzeptiert. Das System kennt nur die Werte, welche online eingegeben wurden.

      Bitte verwenden Sie für den Druck *kein grünes oder sehr dunkles Papier*.

      Die Preisschilder sollten so an der Ware angebracht werden, dass das Etikett nicht verloren
      gehen kann. Hierbei helfen z.B. Lochverstärker und starke Bindfäden – Bitte verwenden Sie
      keine Sicherheitsnadeln und tackern nichts an der Ware fest (Verletzungs- und
      Beschädigungsgefahr!). Die Etiketten dürfen auch laminiert oder geklebt werden, sofern dies
      nicht die Ware beschädigt.

      Jeder Artikel erhält ein Preisschild, sofern sie nicht irgendwelche Sets, z.B. Zweiteiler verkaufen
      wollen. In diesem Fall verbinden sie das jeweilige Set gut miteinander.

      ### Anzahl der zu verkaufenden Artikel

      Es dürfen nur maximal 100 Kleidungsstücke und maximal 3 Paar Schuhe angeboten werden.
      Bücher, Spielsachen, Fuhrpark, Babydecken etc. sind in unbegrenzter Anzahl zum Verkauf
      möglich.

      Die Ware ist nach Größe vorzusortieren und durch eine Lage Zeitungspapier deutlich zu trennen.

      Zur Anlieferung haben sich Kartons oder ähnlich stabile Objekte, die Sie bitte mit dem über
      unser System erzeugten Karton-Etikettenschild beschriften, bewährt. Jeder Anbieter
      bekommt seine nicht verkaufte Ware in seinen mitgebrachten Verpackungsmaterialien wieder zurück.

      Es kommt leider immer wieder vor, dass manche Ware in einem schlechten Zustand (kaputt,
      unvollständig, schmutzig, zerrissen, übel riechend etc.) ist, wenn sie gebracht wird. Diese Ware
      wird nicht in den Verkauf gegeben. Achten Sie also auch in Ihrem Sinne darauf, dass die Ware in
      einem guten Zustand bei uns ankommt.

      Des Weiteren möchten wir Sie darauf hinweisen, dass allzu große Kleiderbündel (z.B.
      Strumpfhosen, Unterwäsche etc.) viel Platz einnehmen und erfahrungsgemäß nicht gut verkauft
      werden. Kleinere Textilien, wie z.B. Socken, sollten in durchsichtigen Tüten, die sich öffnen lassen,
      verpackt werden, damit der Kunde die Ware ausreichend in Augenschein nehmen kann.

      Bei Steck-/Puzzle oder ähnlichen Dingen sollte darauf geachtet werden, dass diese in einer
      durchsichtigen Tüte präsentiert werden, um einen Verlust einzelner Teile zu vermeiden.
      Denken Sie beim Auszeichnen und Verpacken bitte auch daran, dass die Artikel auf Tischen liegen
      und unter Umständen von vielen Personen in die Hand genommen werden.

      ### Bring- und Abholzeiten für die Ware

      Die genauen Bring- und Abholzeiten finden Sie auf der [Hauptseite](/).

      Bitte kommen Sie pünktlich und bringen Ihren Ausweis und Ihre Anbieternummer (Infobrief)
      mit. Ihre Abrechnung und die nicht verkaufte Ware sollten Sie vor Ort überprüfen, da spätere
      Reklamationen wegen fehlender Nachvollziehbarkeit leider nicht berücksichtigt werden
      können.

      Sollten Sie Ihre Ware und den Verkaufserlös nicht bis zum Ende der Abholzeit bei uns abgeholt
      haben, behalten wir uns vor, die Waren an das Caritasbüro Durlach für wohltätige Zwecke zu
      spenden. Es besteht auch die Möglichkeit die Ware direkt im Warensystem als Spende zu
      kennzeichnen, sodass die nicht verkaufte Ware gespendet und nicht an Sie zurückgegeben wird.
      Falls Ihnen beim Abholen etwas dazwischen kommt, können Sie eine andere Person per
      Vollmacht beauftragen, die Sachen für Sie abzuholen.

      ### Sicherheit

      Der Kommissionsflohmarkt wird von Ehrenamtlichen durchgeführt. Wir übernehmen keinerlei
      Haftung für abhanden gekommene, unvollständige oder beschädigte Artikel. Für die
      Rückgabe von Kleiderbügeln kann keine Gewähr übernommen werden.

      ### Verschiedenes

      Bei Fragen erreichen Sie uns unter Tel.: 0721/ 47 662 99 oder der Emailadresse:

      kommi-flohmarkt-durlach@flohmarkthelfer.de
    mail:
      from: Kommi-Flohmarkt Durlach <kommi-flohmarkt-durlach@flohmarkthelfer.de>
    price_precision: 0.5
    commission_rate: 0.3
    seller_fee: 0.0
    donation_of_unsold_items_enabled: true
    prefix: 6
hosts:
  durlach.localhost: durlach
  durlach.flohmarkthelfer.de: durlach
  kommi-flohmarkt-durlach.flohmarkthelfer.de: durlach
