brands:
  eggenfelden:
    name: Kinderflohmarkt Rottgauhalle Eggenfelden
    name_html: Kinderflohmarkt Rottgauhalle Eggenfelden
    home:
      logo:
      intro: |
        **Rottgauhalle, Grafenweg 11, 84307 Eggenfelden
      outro: |
        Hier finden Sie uns:

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2648.9849356759046!2d12.771200251534657!3d48.39923244077716!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4775b97011487e61%3A0xbe3e6048c997acc9!2sRottgauhalle!5e0!3m2!1sen!2sde!4v1497085268363" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    contact: kinderflohmarkt-rottgauhalle@flohmarkthelfer.de
    imprint:
      address:
        - Lehmann Software Lösungen GbR
        - Am Schlossgarten 14
        - 75203 Königsbach
      contact: imprint@flohmarkthelfer.de
    terms: |
      **In Kommission genommen werden** gut erhaltene, gewaschene Baby- und Kinderbekleidung
      für die kommende Jahreszeit bis Größe 176, Umstandsmode, Schuhe (paarweise gebündelt),
      Autositze, Rutschautos, Kettcars, Fahrräder, Spielsachen etc., aber keine Kinderwägen und Buggys.

      ### WICHTIG!

      Die Ware muss ...

      1. zuvor in unserem Warensystem komplett eingetragen worden sein,
      2. einzeln mit dem entsprechenden Etikett ausgezeichnet sein.
         **Der Barcode und die Zahl darunter muss vollständig lesbar und sauber sein.**
         **Es werden nur Etiketten akzeptiert, die mit unserem System erzeugt wurden.**
      3. in einem **Karton/Wäschekorb** angeliefert werden, der mit der
         **Teilnehmernummer gut sichtbar** gekennzeichnet ist (mehrteilige Kleidungsstücke bitte zusammennähen),
      4. in einem **einwandfreien und zeitgemäßen Zustand** sein

      Falsch ausgezeichnete Ware oder solche mit abgefallenen Etiketten kann von uns leider nicht verkauft werden.
      Wir legen Wert auf einwandfreie, zeitgemäße Ware und behalten uns vor, Teile auszusortieren.

      Für die abgegebene Ware kann (bei Beschädigung und Diebstahl) **keine Haftung** übernommen werden.
      Für die Rückgabe von Kleiderbügeln kann keine Gewähr übernommen werden.

      Es entfällt pro Reservierung eine **Reservierungsgebühr** von **2,50 €**.

      **Um den Verkauf zu erleichtern, bitten wir Sie, nur volle oder halbe Eurobeträge zu notieren. Wir runden
      sonst gegebenenfalls ab.**

      Nur ein Teilnehmer je Haushalt. Mehrere Anmeldungen des gleichen Haushaltes sind nicht gestattet. Wir
      behalten uns das Recht vor, Mehrfachreservierungen aus dem gleichen Haushalt wieder freizugeben.

      Die Teilnehmer müssen die nicht verkaufte Ware, sowie den Erlös der verkauften Teile **sofort kontrollieren**.
      Eine spätere Reklamation ist nicht zulässig.

      Holen Sie bitte Ihre nicht verkauften Teile und Ihren Erlös im festgelegten Zeitraum ab. Für nicht
      abgeholte Ware berechnen wir eine **Lagergebühr von 5 €**. Nach Ablauf einer einwöchigen Lagerung geht das
      Eigentum an der nicht abgeholten Ware an das Flohmarktteam über.

      Leider kann es trotz großer Sorgfalt vorkommen, dass ein Kleidungsstück falsch einsortiert wurde. Sollte dies
      der Fall sein, möchten wir Sie bitten, Teile, die Ihnen nicht gehören, umgehend an uns zurückzugeben.

      ### Drucken der Etiketten

      Wir arbeiten beim Verkauf mit Scannern und akzeptieren daher nur Waren mit unseren Etiketten,
      welche Sie nach Artikeleingabe erzeugen und drucken.

      Handschriftliche Änderungen auf den Etiketten werden nicht akzeptiert.
      Das System kennt nur die Werte, welche online eingegeben wurden.

      Bitte verwenden Sie für den Druck **kein grünes oder sehr dunkles Papier**.

      Die Etiketten dürfen laminiert oder geklebt werden, sofern dies nicht die Ware beschädigt.

      ### Verkaufserlös

      **20% des Umsatzes sind ausschließlich für die Kinder- und Jugendarbeit in der Matthäusgemeinde
      bestimmt. Alle beteiligten Personen arbeiten ehrenamtlich.**
    mail:
      from: Kinderflohmarkt Rottgauhalle Eggenfelden <kinderflohmarkt-rottgauhalle@flohmarkthelfer.de>
    price_precision: 0.5
    commission_rate: 0.2
    seller_fee: 2.5
    donation_of_unsold_items_enabled: false
    prefix: 9
hosts:
  eggenfelden.localhost: eggenfelden
  eggenfelden.flohmarkthelfer.de: eggenfelden
  kinderflohmarkt-rottgauhalle.flohmarkthelfer.de: eggenfelden
