brands:
  rueppurr:
    name: Kinder-Secondhand-Markt
    name_html: Kinder-Secondhand-Markt
    home:
      logo:
      intro:
      outro: |
        Hier unser [Flyer für unseren 41. Kinder-Secondhand-Markt](rueppurr/flyer2016.pdf).
        Sie können hier auch [unseren Lageplan](rueppurr/plan.pdf) sehen.
    contact: kinder-shm@flohmarkthelfer.de
    imprint:
      address:
        - Lehmann Software Lösungen GbR
        - Am Schlossgarten 14
        - 75203 Königsbach
      contact: imprint@flohmarkthelfer.de
    terms: |
      ### WICHTIG!

      Die Ware muss...

      1. zuvor in unserem Warensystem komplett eingetragen worden sein,
      2. einzeln mit dem entsprechenden Etikett ausgezeichnet sein.
         **Der Barcode und die Zahl darunter müssen vollständig lesbar und sauber sein.**
         **Es werden nur Etiketten akzeptiert, die mit unserem System erzeugt wurden.**
      3. in einem stabilen **Karton** angeliefert werden, der mit der **Teilnehmernummer gut sichtbar**
         gekennzeichnet ist.
      4. in einem **einwandfreien Zustand** sein

      ### Artikel:

      **In Kommission genommen werden** gut erhaltene, saubere Baby- und Kinderbekleidung bis
      Größe 164 (Keine Erwachsenenkleidung), Spiele und Bücher, Sportartikel (Rollschuhe,
      Schlittschuhe, Roller, Fahrräder), Schuhe, Fahrradsitze + -helme, Autositze (mit der gültigen
      Norm ECE R 44/03 oder 44/04). Babyausstattungen, Kinderwagen.

      **Nicht verkauft** werden sperrige, große Babymöbel, Töpfchen, zusammengefasste Hosen,
      Kleider und Pullis. Außerdem sortieren wir fleckige, kaputte/ unvollständige und schlecht
      riechende Artikel aus.

      Pro Anbieter darf eine **begrenzte Anzahl** von Artikeln in Kommission gegeben werden. Es
      werden nur Preise akzeptiert, die auf 50 Cent gerundet sind.

      Bitte sorgen Sie dafür, dass Ihre Etiketten **gut an den Artikeln befestigt** sind, da wir für Verlust
      oder Vertauschen derselben nicht haften können. Falsch ausgezeichnete Ware oder solche mit
      abgefallenen Etiketten kann von uns leider nicht verkauft werden. Schuhe müssen paarweise
      zusammengebunden werden- nicht nur mit den Schnürsenkeln, Spiele sollten vollständig und
      gesichert sein. Bitte das Etikett wegen Verletzungsgefahr nicht mit Tacker oder Nadeln
      befestigen!

      ### Drucken der Etiketten:

      Wir arbeiten beim Verkauf mit Scannern und akzeptieren daher nur Waren mit unseren Etiketten,
      welche Sie nach Artikeleingabe erzeugen und ausdrucken können.

      Handschriftliche Änderungen auf den Etiketten werden nicht akzeptiert.
      Das System kennt nur die Werte, welche online eingegeben wurden.

      Bitte verwenden Sie für den Druck **kein rotes oder sehr dunkles Papier**.

      Die Etiketten dürfen laminiert oder auf festeren Karton geklebt werden.

      Sollten Sie keine Möglichkeit haben, die Etiketten selbst zu drucken, kontaktieren Sie uns bitte.

      ### Sonstiges:

      Wir runden alle **Verkäuferauszahlungsbeträge** auf volle 50 Cent ab. D.h. aus 10,88 € werden 10,50 €.

      **Nicht zurücksortiert** und damit als Spende betrachtet werden: Schuhe, Accessoires, wie z.B.
      Gürtel, Unterwäsche, Bodies, Strumpfhosen, Socken, Mützen, Schals, Handschuhe,
      Badekleidung und Plüschtiere.

      Prüfen Sie bitte Ihre **restliche Ware** nach Erhalt. Bitte eventuell falsch einsortierte oder fehlende
      Ware sofort bei uns reklamieren. Ware ohne Kennzeichnung (vergessene oder abgelöste
      Etiketten) liegt am Abholtermin aus. Nicht abgeholte Ware wird zum Ende des festgelegten
      Abholzeitraums den Spenden zugeteilt.

      ### Haftung:

      Das Secondhand-Markt-Team haftet nicht bei Diebstahl, Verlust oder Beschädigung der zur
      Verfügung gestellten Ware. Berücksichtigen Sie dies bei wertvollen Artikeln.

      ### Verkaufserlös:

      Als Unkostenbeitrag behalten wir 25% des Erlöses ein, der damit erzielte Gewinn geht zu 100%
      an soziale Projekte und Organisationen mit Schwerpunkt Kinder und Familie.
    mail:
      from: Kinder-Secondhand-Markt Rüppurr <kinder-shm@flohmarkthelfer.de>
    price_precision: 0.5
    commission_rate: 0.25
    seller_fee: 2.0
    donation_of_unsold_items_enabled: true
    donation_of_unsold_items_default: true
    prefix: 2
hosts:
  rueppurr.localhost: rueppurr
  rueppurr.flohmarkthelfer.de: rueppurr
  kinder-shm.flohmarkthelfer.de: rueppurr
  www.kinder-shm.flohmarkthelfer.de: rueppurr
