hosts:
  koenigsbach.test.flohmarkthelfer.de: koenigsbach
  ersingen.test.flohmarkthelfer.de: ersingen
  dammerstock.test.flohmarkthelfer.de: dammerstock

  koenigsbach.flohmarkthelfer.de: koenigsbach
  flohmarkt-koenigsbach.de: koenigsbach

  ersingen.flohmarkthelfer.de: ersingen
  flohmarkt-ersingen.de: ersingen

  friedensgemeinde.flohmarkthelfer.de: dammerstock
